# k8s-manifests/argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app-prod
  namespace: argocd
spec:
  project: default
  source:
    # Використовуємо внутрішній DNS кластера або наш домен
    repoURL: 'https://github.com/andreas-prinz/devops-diploma-project.git'
    targetRevision: HEAD
    path: k8s-manifests # папка, де лежить твій rollout.yaml
  destination:
    server: 'https://34.32.110.187'
    namespace: diploma-prod
  syncPolicy:
    automated:
      prune: true
      selfHeel: true
