// Jenkinsfile Groovy
pipeline {
    agent {
        node {
            label 'built-in'
            // Вказуємо Jenkins автоматично працювати всередині цієї папки
            customWorkspace "2-go-app"
        }
    }
    
    environment {
        APP_NAME = "go-app"
        DOCKER_USER = "andreasprinz"
        DOCKER_PASS = "dockerhub-deploy-token"
	DOCKER_IMAGE = "${DOCKER_USER}" + "/" + "${APP_NAME}"
        // Приклад адреси Nexus у кластері:
//        DOCKER_IMAGE = "nexus-nexus-repository-manager.nexus.svc.cluster.local:8082/go-app"
        VERSION = "v${env.BUILD_NUMBER}"
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout from SCM') {
            steps {
                git branch: 'master', credentialsId: 'github-deploy-token', url: 'https://github.com/andreas-prinz/devops-diploma-project'
//                checkout scm
            }
        }

        stage('Test') {
            steps {
                // -v дає детальний лог кожного тесту
                // -race перевіряє код на проблеми з конкурентністю (race conditions)
                sh 'go test -v -race ./...'
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
//                    sh "docker build -t ${DOCKER_IMAGE}:${VERSION} ."
//                    sh "docker push ${DOCKER_IMAGE}:${VERSION}"
                    docker.withRegistry('',DOCKER_PASS) {
                        docker_image = docker.build "${DOCKER_IMAGE}"
                        docker_image.push("${VERSION}")
                        docker_image.push("latest")
                    }
                }
            }
        }

        stage('Cleanup Artifacts') {
            steps {
                sh "docker rmi ${DOCKER_IMAGE}:${VERSION}"
                sh "docker rmi ${DOCKER_IMAGE}:latest"
            }
        }

        stage('Update Manifests (GitOps)') {
            steps {
                // Jenkins заходить у репозиторій з маніфестами і змінює тег образу
                // Це тригерить ArgoCD на розгортання
                sh """
#                   rm -rf manifests-repo
                   # Копіюємо з внутрішнього GitLab
#                   git clone http://gitlab-webservice.gitlab.svc.cluster.local/root/go-app-manifests.git manifests-repo
#                   cd manifests-repo
#                   sed -i 's|image: .*|image: ${DOCKER_IMAGE}:${VERSION}|' k8s-manifests/rollout.yaml
#                   git add k8s-manifests/rollout.yaml
#                   git commit -m "Update image to ${VERSION}"
#                   git push origin main
                """
            }
        }
    }
}
