// Jenkinsfile Groovy
pipeline {
    agent {
        node {
            label 'built-in'
            // Вказуємо Jenkins автоматично працювати всередині цієї папки
            customWorkspace "2-go-app"
        }
    }

    tools {
        go 'go-1.26.3' 
    }
    
    environment {
        APP_NAME = "go-app"
        DOCKER_USER = "andreasprinz"
        DOCKER_PASS = "dockerhub-deploy-token"
	DOCKER_IMAGE = "${DOCKER_USER}" + "/" + "${APP_NAME}"
        // Приклад адреси Nexus у кластері:
//        DOCKER_IMAGE = "nexus-nexus-repository-manager.nexus.svc.cluster.local:8082/go-app"
        VERSION = "v${env.BUILD_NUMBER}"
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout from SCM') {
            steps {
                git branch: 'master', credentialsId: 'github-deploy-token', url: 'https://github.com/andreas-prinz/devops-diploma-project'
//                checkout scm
            }
        }

        stage('Test') {
            steps {
//                withEnv(['CGO_ENABLED=1']) {
                    sh 'pwd'
                    sh 'ls -la'
                    sh '''
                        if [ ! -f go.mod ]; then
                            go mod init my-diploma-app
                            go mod tidy
                        fi
                    '''
                    // -v дає детальний лог кожного тесту
                    // -race перевіряє код на проблеми з конкурентністю (race conditions)
                    sh 'go test -v ./...'
//                }
            }
        }

        stage('Build & Push Docker Image') {
            agent {
                kubernetes {
                    customWorkspace "2-go-app"
                    yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.20.0-debug
    command: ["sleep"]
    args: ["99d"]
    tty: true
    volumeMounts:
    - name: registry-credentials
      mountPath: /kaniko/.docker
  volumes:
  - name: registry-credentials
    emptyDir: {}
'''
                }
            }
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-deploy-token', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    container('kaniko') {
                        sh """
                            echo "{\\"auths\\":{\\"https://docker.io\\":{\\"auth\\":\\"$(echo -n ${DOCKER_USER}:${DOCKER_PASS} | base64 | tr -d '\\n')\\"}}}" > /kaniko/.docker/config.json
                            
                            /kaniko/executor \
                              --context=. \
                              --dockerfile=Dockerfile \
                              --destination=${DOCKER_IMAGE}:${VERSION} \
                              --destination=${DOCKER_IMAGE}:latest
                        """
                    }
                }
            }
        }
            
//                script {
//                    sh "docker build -t ${DOCKER_IMAGE}:${VERSION} ."
//                    sh "docker push ${DOCKER_IMAGE}:${VERSION}"
//                    docker.withRegistry('',DOCKER_PASS) {
//                        docker_image = docker.build "${DOCKER_IMAGE}"
//                        docker_image.push("${VERSION}")
//                        docker_image.push("latest")
//                    }
//                }
//            }
//        }

//        stage('Cleanup Artifacts') {
//            steps {
//                sh "docker rmi ${DOCKER_IMAGE}:${VERSION}"
//                sh "docker rmi ${DOCKER_IMAGE}:latest"
//            }
//        }

        stage('Update Manifests (GitOps)') {
            steps {
                // Jenkins заходить у репозиторій з маніфестами і змінює тег образу
                // Це тригерить ArgoCD на розгортання
                sh """
#                   rm -rf manifests-repo
                   # Копіюємо з внутрішнього GitLab
#                   git clone http://gitlab-webservice.gitlab.svc.cluster.local/root/go-app-manifests.git manifests-repo
#                   cd manifests-repo
#                   sed -i 's|image: .*|image: ${DOCKER_IMAGE}:${VERSION}|' k8s-manifests/rollout.yaml
#                   git add k8s-manifests/rollout.yaml
#                   git commit -m "Update image to ${VERSION}"
#                   git push origin main
                """
            }
        }
    }
}
