// Jenkinsfile Groovy
pipeline {
    agent {
        node {
            label 'built-in'
        }
    }

    tools {
        go 'go-1.26.3' 
    }
    
    environment {
        APP_NAME = "go-app"
        DOCKER_USER = "andreasprinz"
        DOCKER_PASS = "dockerhub-deploy-token"
	DOCKER_IMAGE = "${DOCKER_USER}" + "/" + "${APP_NAME}"
        // Приклад адреси Nexus у кластері:
//        DOCKER_IMAGE = "nexus-nexus-repository-manager.nexus.svc.cluster.local:8082/go-app"
        VERSION = "v1.0.0-b${BUILD_NUMBER}"
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout from SCM') {
            steps {
                git branch: 'master', credentialsId: 'github-deploy-token', url: 'https://github.com/andreas-prinz/devops-diploma-project'
//                checkout scm
            }
        }

        stage('Test') {
            steps {
//                withEnv(['CGO_ENABLED=1']) {
                dir('2-go-app') {
                    sh 'pwd'
                    sh 'ls -la'
                    sh '''
                        if [ ! -f go.mod ]; then
                            go mod init my-diploma-app
                            go mod tidy
                        fi
                    '''
                    // -v дає детальний лог кожного тесту
                    // -race перевіряє код на проблеми з конкурентністю (race conditions)
                    sh 'go test -v ./...'
//                }
                }
            }
        }

        stage('Build & Push Docker Image') {
            agent {
                kubernetes {
                    yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker-cli
    image: docker:27.0-cli
    command: ["cat"]
    tty: true
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
  - name: dind
    image: docker:27.0-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
'''
                }
            }
            
            steps {
                withEnv(["DOCKER_IMAGE=${DOCKER_IMAGE}", "VERSION=${VERSION}"]) {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-deploy-token', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        container('docker-cli') {
                            sh '''
                                sleep 5
                                cd 2-go-app/
                                if [ ! -f go.mod ]; then
                                    go mod init my-diploma-app
                                    go mod tidy
                                fi
                                ls -la                        
                                echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
                        
                                docker build -t ${DOCKER_IMAGE}:${VERSION} -t ${DOCKER_IMAGE}:latest .
                        
                                docker push ${DOCKER_IMAGE}:${VERSION}
                                docker push ${DOCKER_IMAGE}:latest
                            '''
                        }
                    }
                }
            }
        }
            
        stage('Update Manifests (GitOps)') {
            steps {
                // Jenkins заходить у репозиторій з маніфестами і змінює тег образу
                // Це тригерить ArgoCD на розгортання
                sh """
#                   rm -rf manifests-repo
                   # Копіюємо з внутрішнього GitLab
#                   git clone http://gitlab-webservice.gitlab.svc.cluster.local/root/go-app-manifests.git manifests-repo
#                   cd manifests-repo
#                   sed -i 's|image: .*|image: ${DOCKER_IMAGE}:${VERSION}|' k8s-manifests/rollout.yaml
#                   git add k8s-manifests/rollout.yaml
#                   git commit -m "Update image to ${VERSION}"
#                   git push origin main
                """
            }
        }
        
        stage('Deploy to K8s') {
            agent {
                kubernetes {
                    containerTemplate(
                        name: 'kubectl', 
                        image: alpine/kubectl:1.36.1,
                        ttyEnabled: true,
                        command: 'cat'
                    )
                    serviceAccount 'jenkins' 
                }
            }
            
            steps {
//                dir('3-k8s-manifests') {
                    container('kubectl') {
                        withEnv(["DOCKER_IMAGE=${DOCKER_IMAGE}", "VERSION=${VERSION}"]) {
                            sh '''
                                set -x
                                apk add --no-cache git
                                git clone https://github.com/andreas-prinz/devops-diploma-project.git
                                cd devops-diploma-project/3-k8s-manifests
                                pwd
                                ls -la
                                kubectl apply -f app-deployment.yaml
                                
                                kubectl set image deployment/go-app go-app-container=${DOCKER_IMAGE}:${VERSION}
                                
                                kubectl rollout status deployment/go-app --timeout=60s
                            '''
                        }
                    }
//                }
            }
        }
    }
}
